apiVersion: v1
kind: Service
metadata:
  name: mongodb-internal-loadbalancer
  labels:
    name: mongos-router
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    role: mongos-router
  ports:
    - port: 30000
      targetPort: 27017
      protocol: TCP
