apiVersion: v1
kind: Service
metadata:
  name: mongodb-configdb-service
  labels:
    name: mongo-configdb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo-configdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod-configdb
spec:
  serviceName: mongodb-configdb-service
  replicas: 3
  selector:
    matchLabels:
      role: mongo-configdb
      tier: configdb
      replicaset: ConfigDBReplicaSet
  template:
    metadata:
      labels:
        role: mongo-configdb
        tier: configdb
        replicaset: ConfigDBReplicaSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - ConfigDBReplicaSet
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      volumes:
        - name: secrets-volume
          secret:
            secretName: shared-bootstrap-data
            defaultMode: 256
        - name: config-volume
          configMap:
            name: cm-mongo-configdb
      containers:
        - name: mongod-configdb-container
          image: mongo:4.2.12
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "-f"
            - "/etc/config/mongo-configdb.conf"
          resources:
            requests:
              cpu: 1.5
              memory: 4Gi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
            - name: mongo-configdb-persistent-storage-claim
              mountPath: /data/configdb
            - name: config-volume
              mountPath: /etc/config
  volumeClaimTemplates:
  - metadata:
      name: mongo-configdb-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 15Gi
