apiVersion: v1
kind: Service
metadata:
  name: mongos-router-service
  labels:
    name: mongos-router
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongos-router
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongos-router
spec:
  serviceName: mongos-router-service
  replicas: 3
  selector:
    matchLabels:
      role: mongos-router
      tier: routers
      replicaset: routers
  template:
    metadata:
      labels:
        role: mongos-router
        tier: routers
        replicaset: routers
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - routers
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      volumes:
        - name: secrets-volume
          secret:
            secretName: shared-bootstrap-data
            defaultMode: 256
        - name: mongos-volume
          configMap:
            name: cm-mongo-router
      containers:
        - name: mongos-container
          image: mongo:4.2.12
          command:
            - "numactl"
            - "--interleave=all"
            - "mongos"
            - "-f"
            - "/etc/config/mongo-router.conf"
          resources:
            requests:
              cpu: 0.25
              memory: 512Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
            - name: mongos-volume
              mountPath: /etc/config


